# Generated by Django 2.2 on 2022-05-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
